-- TimescaleDB Hypertable Conversion
-- This file contains the SQL commands to convert the prices table to a hypertable
-- for time-series optimization. Execute this AFTER running `drizzle-kit push`.

-- Note: The actual CREATE TABLE prices statement will be auto-generated by Drizzle
-- This file only contains the TimescaleDB-specific commands

-- Convert the prices table to a hypertable with automatic time-based partitioning
-- Chunk interval: 7 days (optimal for medium-frequency data)
SELECT create_hypertable('prices', 'timestamp', chunk_time_interval => INTERVAL '7 days');

-- Verify hypertable creation
SELECT hypertable_name, time_column_name, chunk_time_interval
FROM timescaledb_information.hypertables
WHERE hypertable_name = 'prices';
